### PR TITLE
added regex

### PR DESCRIPTION
**Pull request by j2l**
Hi,
To help this great idea, I added a few regex I got.

### CODE REVIEW

**Comment by Shaderboy** [comment]
Hey, thanks for these! It looks like line 37 is causing some issues with the test case you mentioned in the issue. I'll merge this if you fix that/take it out.

**Comment by j2l** [comment]
Sure, done :)

**Review by Shaderboy — CHANGES_REQUESTED** [review]
Please add the new commit fixing/nixing line 37. Also, the existing while loop from lines 36-60 does what the pattern at this commit's line 36 intends to do, so better to take that out I think. Otherwise, it looks good!

**Comment by j2l** [comment]
I updated the patch

**Review by Shaderboy — APPROVED** [review]

**Comment by Shaderboy** [comment]
Woops it looks like it's trying to merge your master branch instead of your patch branch (it only lists 2 total commits instead of 5).

**Comment by j2l** [comment]
Weird, I had to create a patch brach to request the pull. I'll sync master to patch branch.

**Comment by j2l** [comment]
Should be OK now.

**Pull request merged**
